
services:
  db:
    image: postgres:14
    container_name: bbrf_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bbrf_net

  bbrf_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bbrf_server
    ports:
      - "8443:8443"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - bbrf_net

volumes:
  db_data:

networks:
  bbrf_net:

